#!/bin/sh

########################################
########################################
####                                 ###
####   ALPINE ROUTER CONFIGURATION   ###
####                                 ###
########################################
########################################

echo "Checking for dependencies..."

HOSTAPD=$(apk info | grep hostapd)
DNSMASQ=$(apk info | grep dnsmasq)
IPTABLES=$(apk info | grep iptables)

if [  "$HOSTAPD" =  "" ];then
	echo "Adding hostapd"
	apk add hostapd
else
	service hostapd stop
fi

if [  "$DNSMASQ" =  "" ];then
	echo "Adding dnsmasq"
	apk add dnsmasq
else
	service dnsmasq stop
fi

if [  "$IPTABLES" =  "" ];then
	echo "Adding adding iptables"
	apk add iptables
fi

echo "Moving config files..."

mv files/hostapd.conf /etc/hostapd/hostapd.conf
mv files/dnsmasq.conf /etc/dnsmasq.conf
mv files/interfaces /etc/network/interfaces 

echo "Configure iptables..."

iptables --flush
iptables --table nat --flush
iptables --delete-chain
iptables --table nat --delete-chain
iptables --table nat --append POSTROUTING --out-interface eth0 -j MASQUERADE
iptables --append FORWARD --in-interface wlan0 -j ACCEPT

sysctl -w net.ipv4.ip_forward=1

#################################################
############ SET UP THE NETWORK #################
#################################################


################# START WIFI ####################

if [ "$(ip link | grep wlan0)" ]
then
  echo "Killing WiFi."
  ifconfig wlan0 down
  sleep 1s
fi

echo "Starting wifi."
ifconfig wlan0 up 10.0.0.1 netmask 255.255.255.0
sleep 2s

echo "Starting wireless access point."
service hostapd start
service dnsmasq start

